version: "3.7"
services:
    server:
        build: ./server
        container_name: server
        restart: always
        ports:
            - "8000:8000"

    peeram:
        build: ./peeram
        container_name: peeram
        restart: always
        ports:
            - 8001
            
    peernz:
        build: ./peernz
        container_name: peernz
        restart: always
        ports:
            - 8002

    databaseam:
        build: ./databaseam
        container_name: databaseam
        restart: always
        environment:
                    MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306
            
    databasenz:
        build: ./databasenz
        container_name: databasenz
        restart: always
        environment:
                    MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306
